---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-mongo
  namespace: demo
  labels:
    app: demo-mongo
spec:
  selector:
    matchLabels:
      app: demo-mongo
  serviceName: demo-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              name: mongo
          resources:
            requests:
              cpu: 250m
              memory: 256M
            limits:
              cpu: 500m
              memory: 1G
          env:
            - name:  MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopw
---
apiVersion: v1
kind: Service
metadata:
  name: demo-mongo
  namespace: demo
  labels:
    app: demo-mongo
spec:
  ports:
    - port: 27017
      name: demo-mongo
  selector:
    app: demo-mongo
